// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrmcjkbbvgyjplxlmhch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhybWNqa2Jidmd5anBseGxtaGNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg2MjE0ODMsImV4cCI6MjA4NDE5NzQ4M30.hgg9YNtSSlcXc-e9inDyPWs71QlusARDH3Y0TeQneK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});